### ISSUE TITLE
[Bug] Corpse Party Blood Covered on PSP

### ISSUE THREAD

**Issue by lolcatw** [vgmstream/vgmstream#1440]
Hello!

When using this library, I am not able to decode the audio files @ `PSP_GAME/USRDIR/VO00.AFS/`, on the PSP game Corpse Party Blood Covered on PSP. When playing the files back, I can sort of hear the audio but with lots of noise layered on top. The files were unpacked using AFSPacker ([here](https://github.com/MaikelChan/AFSPacker))

Thanks..

**Comment by bnnm** [comment]
Fixed: https://vgmstream.org/

**Comment by lolcatw** [comment]
It's still not fixed. Let me give you a file to demonstrate

https://files.catbox.moe/2wh8n6.adx

The original file sounds clear and has no noise. Please lower your volume before playing. FFMPEG also fails to decode it properly. Probably has to do with the fact that this file has 2 audio channels and that most specifications for this format only use 1 channel.

**Comment by bnnm** [comment]
Sounds fine here, using components from vgmstream.org.

If you are building the project yourself remember to do a full rebuild (or force recompile adx.c). It just needs a decryption key, which was added in the last commits.

**Comment by lolcatw** [comment]
My bad, I thought the web interface was updated. Let me take another look.

**Comment by lolcatw** [comment]
Oh my god it fucking works ;) thank you so much
